{
 "title": "BSSR",
 "time": { "from": "2023-10-24T12:10:08.324Z", "to": "2023-10-27T05:47:39.662Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"bssr\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"MCMB\" or r[\"_field\"] == \"PPTMB\")\n  |> filter(fn: (r) => r[\"host\"] == \"telem\")\n  |> filter(fn: (r) => r[\"topic\"] == \"bus_metrics/voltage/PPTMB\" or r[\"topic\"] == \"bus_metrics/voltage/MCMB\" or r[\"topic\"] == \"bus_metrics/current/PPTMB\" or r[\"topic\"] == \"bus_metrics/current/MCMB\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Bus Current",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "bus_metrics/current/BBMB" },
    { "topic": "bus_metrics/current/MCMB" },
    { "topic": "bus_metrics/current/PPTMB" }
   ]
  },
  {
   "title": "Target Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bssr\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"target_power\")\n  |> filter(fn: (r) => r[\"host\"] == \"telem\")\n  |> filter(fn: (r) => r[\"topic\"] == \"dcmb/target_power\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Motor Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "bus_metrics/voltage/MCMB" },
    { "topic": "bus_metrics/current/MCMB" }
   ]
  },
  {
   "title": "Motor State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "dcmb/motor_state" }
   ]
  },
  {
   "title": "Target power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "dcmb/target_power" }
   ]
  },
  {
   "title": "VFM Position",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "dcmb/vfm_position" }
   ]
  },
  {
   "title": "Car Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "topic": "mcmb/car_speed" }
   ]
  },
  {
   "title": "Array Power",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bssr\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BBMB\" or r[\"_field\"] == \"MCMB\")\n  |> filter(fn: (r) => r[\"host\"] == \"telem\")\n  |> filter(fn: (r) => r[\"topic\"] == \"bus_metrics/voltage/MCMB\" or r[\"topic\"] == \"bus_metrics/voltage/BBMB\" or r[\"topic\"] == \"bus_metrics/current/MCMB\" or r[\"topic\"] == \"bus_metrics/current/BBMB\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Bus Voltage Live",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "bus_metrics/voltage/BBMB" },
    { "topic": "bus_metrics/voltage/MCMB" },
    { "topic": "bus_metrics/voltage/PPTMB" }
   ]
  },
  {
   "title": "Cell Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"bssr\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"module_5_cell_4\" or r[\"_field\"] == \"module_5_cell_3\" or r[\"_field\"] == \"module_5_cell_2\" or r[\"_field\"] == \"module_5_cell_1\" or r[\"_field\"] == \"module_5_cell_0\" or r[\"_field\"] == \"module_4_cell_4\" or r[\"_field\"] == \"module_4_cell_3\" or r[\"_field\"] == \"module_4_cell_2\" or r[\"_field\"] == \"module_4_cell_1\" or r[\"_field\"] == \"module_4_cell_0\" or r[\"_field\"] == \"module_3_cell_4\" or r[\"_field\"] == \"module_3_cell_3\" or r[\"_field\"] == \"module_3_cell_2\" or r[\"_field\"] == \"module_3_cell_1\" or r[\"_field\"] == \"module_3_cell_0\" or r[\"_field\"] == \"module_2_cell_4\" or r[\"_field\"] == \"module_2_cell_3\" or r[\"_field\"] == \"module_2_cell_2\" or r[\"_field\"] == \"module_2_cell_1\" or r[\"_field\"] == \"module_2_cell_0\" or r[\"_field\"] == \"module_1_cell_4\" or r[\"_field\"] == \"module_1_cell_3\" or r[\"_field\"] == \"module_1_cell_2\" or r[\"_field\"] == \"module_1_cell_1\" or r[\"_field\"] == \"module_1_cell_0\")\n  |> filter(fn: (r) => r[\"topic\"] == \"cell_metrics/voltage/module/1/cell/0\" or r[\"topic\"] == \"cell_metrics/voltage/module/1/cell/1\" or r[\"topic\"] == \"cell_metrics/voltage/module/1/cell/2\" or r[\"topic\"] == \"cell_metrics/voltage/module/1/cell/3\" or r[\"topic\"] == \"cell_metrics/voltage/module/1/cell/4\" or r[\"topic\"] == \"cell_metrics/voltage/module/2/cell/0\" or r[\"topic\"] == \"cell_metrics/voltage/module/2/cell/1\" or r[\"topic\"] == \"cell_metrics/voltage/module/2/cell/2\" or r[\"topic\"] == \"cell_metrics/voltage/module/2/cell/3\" or r[\"topic\"] == \"cell_metrics/voltage/module/2/cell/4\" or r[\"topic\"] == \"cell_metrics/voltage/module/3/cell/0\" or r[\"topic\"] == \"cell_metrics/voltage/module/3/cell/1\" or r[\"topic\"] == \"cell_metrics/voltage/module/3/cell/2\" or r[\"topic\"] == \"cell_metrics/voltage/module/3/cell/3\" or r[\"topic\"] == \"cell_metrics/voltage/module/3/cell/4\" or r[\"topic\"] == \"cell_metrics/voltage/module/4/cell/0\" or r[\"topic\"] == \"cell_metrics/voltage/module/4/cell/1\" or r[\"topic\"] == \"cell_metrics/voltage/module/4/cell/2\" or r[\"topic\"] == \"cell_metrics/voltage/module/4/cell/3\" or r[\"topic\"] == \"cell_metrics/voltage/module/4/cell/4\" or r[\"topic\"] == \"cell_metrics/voltage/module/5/cell/0\" or r[\"topic\"] == \"cell_metrics/voltage/module/5/cell/1\" or r[\"topic\"] == \"cell_metrics/voltage/module/5/cell/2\" or r[\"topic\"] == \"cell_metrics/voltage/module/5/cell/3\" or r[\"topic\"] == \"cell_metrics/voltage/module/5/cell/4\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Array Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "bus_metrics/current/PPTMB" },
    { "topic": "bus_metrics/voltage/PPTMB" }
   ]
  },
  {
   "title": "Max Cell Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bssr\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"module_0_cell_0\" or r[\"_field\"] == \"module_5_cell_2\" or r[\"_field\"] == \"module_5_cell_1\" or r[\"_field\"] == \"module_5_cell_0\" or r[\"_field\"] == \"module_4_cell_1\" or r[\"_field\"] == \"module_4_cell_2\" or r[\"_field\"] == \"module_4_cell_0\" or r[\"_field\"] == \"module_3_cell_0\" or r[\"_field\"] == \"module_2_cell_2\" or r[\"_field\"] == \"module_2_cell_1\" or r[\"_field\"] == \"module_2_cell_0\" or r[\"_field\"] == \"module_1_cell_2\" or r[\"_field\"] == \"module_1_cell_1\" or r[\"_field\"] == \"module_0_cell_2\" or r[\"_field\"] == \"module_1_cell_0\" or r[\"_field\"] == \"module_0_cell_1\")\n  |> filter(fn: (r) => r[\"topic\"] == \"cell_metrics/temperature/module/0/cell/0\" or r[\"topic\"] == \"cell_metrics/temperature/module/0/cell/1\" or r[\"topic\"] == \"cell_metrics/temperature/module/0/cell/2\" or r[\"topic\"] == \"cell_metrics/temperature/module/1/cell/0\" or r[\"topic\"] == \"cell_metrics/temperature/module/1/cell/1\" or r[\"topic\"] == \"cell_metrics/temperature/module/2/cell/0\" or r[\"topic\"] == \"cell_metrics/temperature/module/1/cell/2\" or r[\"topic\"] == \"cell_metrics/temperature/module/2/cell/1\" or r[\"topic\"] == \"cell_metrics/temperature/module/3/cell/0\" or r[\"topic\"] == \"cell_metrics/temperature/module/2/cell/2\" or r[\"topic\"] == \"cell_metrics/temperature/module/4/cell/0\" or r[\"topic\"] == \"cell_metrics/temperature/module/4/cell/1\" or r[\"topic\"] == \"cell_metrics/temperature/module/4/cell/2\" or r[\"topic\"] == \"cell_metrics/temperature/module/5/cell/0\" or r[\"topic\"] == \"cell_metrics/temperature/module/5/cell/1\" or r[\"topic\"] == \"cell_metrics/temperature/module/5/cell/2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bssr\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\n  |> filter(fn: (r) => r[\"host\"] == \"telem\")\n  |> filter(fn: (r) => r[\"topic\"] == \"wind_sensor/speed\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cell SOC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bssr\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"module_5_cell_4\" or r[\"_field\"] == \"module_5_cell_3\" or r[\"_field\"] == \"module_5_cell_2\" or r[\"_field\"] == \"module_5_cell_1\" or r[\"_field\"] == \"module_5_cell_0\" or r[\"_field\"] == \"module_4_cell_4\" or r[\"_field\"] == \"module_4_cell_3\" or r[\"_field\"] == \"module_4_cell_2\" or r[\"_field\"] == \"module_4_cell_1\" or r[\"_field\"] == \"module_4_cell_0\" or r[\"_field\"] == \"module_3_cell_4\" or r[\"_field\"] == \"module_3_cell_3\" or r[\"_field\"] == \"module_3_cell_2\" or r[\"_field\"] == \"module_3_cell_1\" or r[\"_field\"] == \"module_3_cell_0\" or r[\"_field\"] == \"module_2_cell_4\" or r[\"_field\"] == \"module_2_cell_3\" or r[\"_field\"] == \"module_2_cell_2\" or r[\"_field\"] == \"module_2_cell_1\" or r[\"_field\"] == \"module_2_cell_0\" or r[\"_field\"] == \"module_1_cell_4\" or r[\"_field\"] == \"module_1_cell_3\" or r[\"_field\"] == \"module_1_cell_2\" or r[\"_field\"] == \"module_1_cell_1\" or r[\"_field\"] == \"module_1_cell_0\")\n  |> filter(fn: (r) => r[\"topic\"] == \"cell_metrics/soc/module/5/cell/4\" or r[\"topic\"] == \"cell_metrics/soc/module/5/cell/3\" or r[\"topic\"] == \"cell_metrics/soc/module/5/cell/2\" or r[\"topic\"] == \"cell_metrics/soc/module/5/cell/1\" or r[\"topic\"] == \"cell_metrics/soc/module/5/cell/0\" or r[\"topic\"] == \"cell_metrics/soc/module/4/cell/4\" or r[\"topic\"] == \"cell_metrics/soc/module/4/cell/3\" or r[\"topic\"] == \"cell_metrics/soc/module/4/cell/2\" or r[\"topic\"] == \"cell_metrics/soc/module/4/cell/1\" or r[\"topic\"] == \"cell_metrics/soc/module/4/cell/0\" or r[\"topic\"] == \"cell_metrics/soc/module/3/cell/4\" or r[\"topic\"] == \"cell_metrics/soc/module/3/cell/3\" or r[\"topic\"] == \"cell_metrics/soc/module/3/cell/2\" or r[\"topic\"] == \"cell_metrics/soc/module/3/cell/1\" or r[\"topic\"] == \"cell_metrics/soc/module/3/cell/0\" or r[\"topic\"] == \"cell_metrics/soc/module/2/cell/4\" or r[\"topic\"] == \"cell_metrics/soc/module/2/cell/3\" or r[\"topic\"] == \"cell_metrics/soc/module/2/cell/2\" or r[\"topic\"] == \"cell_metrics/soc/module/2/cell/1\" or r[\"topic\"] == \"cell_metrics/soc/module/2/cell/0\" or r[\"topic\"] == \"cell_metrics/soc/module/1/cell/4\" or r[\"topic\"] == \"cell_metrics/soc/module/1/cell/3\" or r[\"topic\"] == \"cell_metrics/soc/module/1/cell/2\" or r[\"topic\"] == \"cell_metrics/soc/module/1/cell/1\" or r[\"topic\"] == \"cell_metrics/soc/module/1/cell/0\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Bus Current Persistent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"bssr\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BBMB\" or r[\"_field\"] == \"MCMB\")\n  |> filter(fn: (r) => r[\"topic\"] == \"bus_metrics/current/MCMB\" or r[\"topic\"] == \"bus_metrics/current/BBMB\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Motor Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "mcmb/motor_temp" }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "wind_sensor/direction" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "topic": "wind_sensor/speed" }
   ]
  },
  {
   "title": "Heartbeats",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "topic": "heartbeats/BBMB" },
    { "topic": "heartbeats/MCMB" },
    { "topic": "heartbeats/PPTMB" },
    { "topic": "heartbeats/DCMB" },
    { "topic": "heartbeats/BMS" }
   ]
  },
  {
   "title": "Cell Temps Persistent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"bssr\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"module_0_cell_0\" or r[\"_field\"] == \"module_5_cell_2\" or r[\"_field\"] == \"module_5_cell_1\" or r[\"_field\"] == \"module_5_cell_0\" or r[\"_field\"] == \"module_4_cell_1\" or r[\"_field\"] == \"module_4_cell_2\" or r[\"_field\"] == \"module_4_cell_0\" or r[\"_field\"] == \"module_3_cell_0\" or r[\"_field\"] == \"module_2_cell_2\" or r[\"_field\"] == \"module_2_cell_1\" or r[\"_field\"] == \"module_2_cell_0\" or r[\"_field\"] == \"module_1_cell_2\" or r[\"_field\"] == \"module_1_cell_1\" or r[\"_field\"] == \"module_0_cell_2\" or r[\"_field\"] == \"module_1_cell_0\" or r[\"_field\"] == \"module_0_cell_1\")\n  |> filter(fn: (r) => r[\"topic\"] == \"cell_metrics/temperature/module/0/cell/0\" or r[\"topic\"] == \"cell_metrics/temperature/module/0/cell/1\" or r[\"topic\"] == \"cell_metrics/temperature/module/0/cell/2\" or r[\"topic\"] == \"cell_metrics/temperature/module/1/cell/0\" or r[\"topic\"] == \"cell_metrics/temperature/module/1/cell/1\" or r[\"topic\"] == \"cell_metrics/temperature/module/2/cell/0\" or r[\"topic\"] == \"cell_metrics/temperature/module/1/cell/2\" or r[\"topic\"] == \"cell_metrics/temperature/module/2/cell/1\" or r[\"topic\"] == \"cell_metrics/temperature/module/3/cell/0\" or r[\"topic\"] == \"cell_metrics/temperature/module/2/cell/2\" or r[\"topic\"] == \"cell_metrics/temperature/module/4/cell/0\" or r[\"topic\"] == \"cell_metrics/temperature/module/4/cell/1\" or r[\"topic\"] == \"cell_metrics/temperature/module/4/cell/2\" or r[\"topic\"] == \"cell_metrics/temperature/module/5/cell/0\" or r[\"topic\"] == \"cell_metrics/temperature/module/5/cell/1\" or r[\"topic\"] == \"cell_metrics/temperature/module/5/cell/2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Bus Voltage Persistent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"bssr\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BBMB\" or r[\"_field\"] == \"MCMB\")\n  |> filter(fn: (r) => r[\"topic\"] == \"bus_metrics/voltage/BBMB\" or r[\"topic\"] == \"bus_metrics/voltage/MCMB\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Cell SOC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"bssr\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"module_5_cell_4\" or r[\"_field\"] == \"module_5_cell_3\" or r[\"_field\"] == \"module_5_cell_2\" or r[\"_field\"] == \"module_5_cell_1\" or r[\"_field\"] == \"module_5_cell_0\" or r[\"_field\"] == \"module_4_cell_4\" or r[\"_field\"] == \"module_4_cell_3\" or r[\"_field\"] == \"module_4_cell_2\" or r[\"_field\"] == \"module_4_cell_1\" or r[\"_field\"] == \"module_4_cell_0\" or r[\"_field\"] == \"module_3_cell_4\" or r[\"_field\"] == \"module_3_cell_3\" or r[\"_field\"] == \"module_3_cell_2\" or r[\"_field\"] == \"module_3_cell_1\" or r[\"_field\"] == \"module_3_cell_0\" or r[\"_field\"] == \"module_2_cell_4\" or r[\"_field\"] == \"module_2_cell_3\" or r[\"_field\"] == \"module_2_cell_2\" or r[\"_field\"] == \"module_2_cell_1\" or r[\"_field\"] == \"module_2_cell_0\" or r[\"_field\"] == \"module_1_cell_4\" or r[\"_field\"] == \"module_1_cell_3\" or r[\"_field\"] == \"module_1_cell_2\" or r[\"_field\"] == \"module_1_cell_1\" or r[\"_field\"] == \"module_1_cell_0\")\n  |> filter(fn: (r) => r[\"topic\"] == \"cell_metrics/soc/module/5/cell/4\" or r[\"topic\"] == \"cell_metrics/soc/module/5/cell/3\" or r[\"topic\"] == \"cell_metrics/soc/module/5/cell/2\" or r[\"topic\"] == \"cell_metrics/soc/module/5/cell/1\" or r[\"topic\"] == \"cell_metrics/soc/module/5/cell/0\" or r[\"topic\"] == \"cell_metrics/soc/module/4/cell/4\" or r[\"topic\"] == \"cell_metrics/soc/module/4/cell/3\" or r[\"topic\"] == \"cell_metrics/soc/module/4/cell/2\" or r[\"topic\"] == \"cell_metrics/soc/module/4/cell/1\" or r[\"topic\"] == \"cell_metrics/soc/module/4/cell/0\" or r[\"topic\"] == \"cell_metrics/soc/module/3/cell/4\" or r[\"topic\"] == \"cell_metrics/soc/module/3/cell/3\" or r[\"topic\"] == \"cell_metrics/soc/module/3/cell/2\" or r[\"topic\"] == \"cell_metrics/soc/module/3/cell/1\" or r[\"topic\"] == \"cell_metrics/soc/module/3/cell/0\" or r[\"topic\"] == \"cell_metrics/soc/module/2/cell/4\" or r[\"topic\"] == \"cell_metrics/soc/module/2/cell/3\" or r[\"topic\"] == \"cell_metrics/soc/module/2/cell/2\" or r[\"topic\"] == \"cell_metrics/soc/module/2/cell/1\" or r[\"topic\"] == \"cell_metrics/soc/module/2/cell/0\" or r[\"topic\"] == \"cell_metrics/soc/module/1/cell/4\" or r[\"topic\"] == \"cell_metrics/soc/module/1/cell/3\" or r[\"topic\"] == \"cell_metrics/soc/module/1/cell/2\" or r[\"topic\"] == \"cell_metrics/soc/module/1/cell/1\" or r[\"topic\"] == \"cell_metrics/soc/module/1/cell/0\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}